### ISSUE TITLE
Please help me 

### ISSUE THREAD

**Issue by naimulhaqueemon** [0x01h/pyddoz#2]
I can't run this script
when i try to run requirments this is shown 
 pip3 install -r requirements.txt
Collecting colorama==0.4.1 (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/4f/a6/728666f39bfff1719fc94c481890b2106837da9318031f71a8424b662e12/colorama-0.4.1-py2.py3-none-any.whl
Collecting proxify==1.0.2 (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/06/d9/2cbe18cbe645e221916919c950631c3b66f8da3850961feba03c1f710f2a/proxify-1.0.2.zip
proxify requires Python '>=2, <=2.8' but the running Python is 3.7.2

when i try to run this module then show
root@kali:~/Desktop/Download/pyddoz# python3 pyddoz.py
Traceback (most recent call last):
  File "pyddoz.py", line 6, in <module>
    import proxify
ModuleNotFoundError: No module named 'proxify'

**Comment by 0x01h** [comment]
"**proxify**" requires a Python version that is below 3.7. Try to run on version **3.5.x.**

**Comment by askl56** [comment]
> "**proxify**" requires a Python version that is below 3.7. Try to run on version **3.5.x.**

`proxify requires Python '>=2, <=2.8' but the running Python is 3.7.2`

Surely we need to use Python 2?

**Comment by askl56** [comment]
Confirmed, does not work: 

```user@host:~/pyddoz# pip3 install -r requirements.txt
Collecting colorama==0.4.1 (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/4f/a6/728666f39bfff1719fc94c481890b2106837da9318031f71a8424b662e12/colorama-0.4.1-py2.py3-none-any.whl
Collecting proxify==1.0.2 (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/06/d9/2cbe18cbe645e221916919c950631c3b66f8da3850961feba03c1f710f2a/proxify-1.0.2.zip
proxify requires Python '>=2, <=2.8' but the running Python is 3.5.7````

**Comment by 0x01h** [comment]
You can follow these steps to make your local Python version compatible with **proxify**:

- Install **pyenv**: https://gist.github.com/jmvrbanac/8793985#file-install_pyenv-sh
```
pyenv install 3.4.0
cd pyddoz-master/
pyenv local 3.4.0
pip install -r requirements.txt
python pyddoz.py
```

**Comment by 0x01h** [comment]
Now, **proxify** module is not a requirement and PyDDoZ is compatible with all Python 3 versions!
