### ISSUE TITLE
"Nuked Requests"? 

### ISSUE THREAD

**Issue by rawandahmad698** [0x01h/pyddoz#3]
I tried Ddos-ing my webserver, I'm not fluent in python but this program doesn't work as expected. 

I would love to get an explanation on these variables: 

Responded Requests: 0 - Nuked Requests: 0 - Bot Requests: 0 - Elapsed Time: 1

**Comment by 0x01h** [comment]
If HTTP connection throws an exception like timeout or server connection error, ```num_failed```variable is incremented which shows total number of **nuked requests**.

**Comment by HILHACKER** [comment]
Not effectively..!!
