### ISSUE TITLE
ModuleNotFoundError: No module named 'colorama'

### ISSUE THREAD

**Issue by nwitked** [0x01h/pyddoz#4]
root@v3nom:~/Documents/pyddoz# python3 pyddoz.py -h
Traceback (most recent call last):
  File "pyddoz.py", line 15, in <module>
    from colorama import Fore, Back
ModuleNotFoundError: No module named 'colorama'

**Comment by 0x01h** [comment]
Did you get error after applying this command?
`pip3 install -r requirements.txt`

Try, `pip3 install colorama`.

**Comment by nwitked** [comment]
Thank you! After that works fine! 
Even i get some other comment: _/usr/local/lib/python3.6/dist-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.2) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)_

The script works like charm!
Thanks again!
